### ISSUE TITLE
[question] why is rsync uninstalled?

### ISSUE THREAD

**Issue by zigotica** [konstruktoid/hardening#128]
Hello, first of all, thank you for this excellent tool. 
Just curious on why `rsync` is uninstalled. I ave not seen any reasoning about this or any other packages. Do you have a link where I can learn more about it?
Thank you

**Comment by konstruktoid** [comment]
Hi @zigotica and thank you.

There's no issues with the `rsync` _client_ per se (you can tunnel it over SSH), the issue is with `rsync --daemon` which is bundled.

See e.g
https://static.open-scap.org/ssg-guides/ssg-rhel8-guide-cis.html#xccdf_org.ssgproject.content_rule_service_rsyncd_disabled
