### ISSUE TITLE
[BUG] Pam_tally config not working

### ISSUE THREAD

**Issue by llouxi** [konstruktoid/hardening#140]
**Describe the bug**
Pam_tally2 counters are not automatically reset after unlock_time.
Accounts must be unlocked manually from cli.

**To Reproduce**
Try to login more than 5 times using a bad password, wait for unlock time and try logging in with the correct password.
The login will fail as pam_tally2 counter is not automatically reset by current config.

**Expected behavior**
Pam_tally2 counters should reset to 0 after unlock_time.

The following config in script password seems to work: 
`if ! grep tally2 "$COMMONACCOUNT"; then
     sed -i '/^$/a account required pam_tally2.so' "$COMMONACCOUNT"    
    fi`

**System (lsb_release -a):**
Tested on Ubuntu 18.04.4 LTS and Ubuntu 20.04.4 LTS

**Additional context**
Reference used for troubleshooting: [https://unix.stackexchange.com/questions/560196/why-does-this-pam-code-prevent-all-logins-to-a-debian-system](url)

**Comment by konstruktoid** [comment]
Hi @llouxi and thanks for opening this issue, I'll have a look at it as soon as possible.

**Comment by konstruktoid** [comment]
When installing on Ubuntu 20.04.4, isn't `faillock` used instead?

**Comment by llouxi** [comment]
Tested again on a fresh install, `faillock` is used on ubuntu 20.04.4 but common-auth is not configured properly so configuration seems partial for faillock.

Current issue is however valid on systems without faillock.

**Comment by konstruktoid** [comment]
Will focus on `faillock` since `pam_tally2` isn't deprecated with `20.04`.

**Comment by konstruktoid** [comment]
```sh
$ grep -v '^#' /etc/pam.d/common-account 
account	[success=1 new_authtok_reqd=done default=ignore]	pam_unix.so 
account	requisite			pam_deny.so
account	required			pam_permit.so
account required pam_faillock.so
```

```sh
grep -v '^#' /etc/pam.d/common-auth 
auth    required pam_faillock.so preauth
auth    [success=1 default=ignore]      pam_unix.so
auth    [default=die] pam_faillock.so authfail
auth    sufficient pam_faillock.so authsucc
auth	requisite			pam_deny.so
auth	required			pam_permit.so
auth	optional			pam_cap.so 
```

**Comment by llouxi** [comment]
thanks for the quick fix, tested and all good now

**Comment by konstruktoid** [comment]
Merged.
