### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by w33ha-zxc** [konstruktoid/hardening#157]
Hi @konstruktoid,

Executing the hardening procedure deletes the home directories for all the users on the system causing loops at the login window.

To Reproduce - 
This issue seems to impact VMs created on HyperV, worked fine with Vmware Workstation.
1. Spin up a VM on HyperV with Ubuntu 22.04.
2. Execute the script.
3. Reboot the server.

executing mkhomedir_helper from recovery mode fixes the issue

HyperV Version: 10.0.17763.1
Replicated for both Ubuntu 20.04 LTS and Ubuntu 22.04 LTS OS

![image](https://user-images.githubusercontent.com/19168627/184083377-ef9d6fb7-25a2-4ce4-b9d5-7ed788ef4345.png)

![image](https://user-images.githubusercontent.com/19168627/184083344-5a0d3b15-c60d-4219-862e-f471f3719005.png)

**Comment by konstruktoid** [comment]
Hi again @w33ha-zxc,
I got no idea why a Ubuntu VM is different on Hyper-V than on AWS, VirtualBox or Workstation.
Did you use an official ISO?

I'll have to find a way to run Hyper-V and then try to debug this.

Can you get some kind of log when the accounts actually gets removed?

**Comment by w33ha-zxc** [comment]
Hi @konstruktoid,

I was wondering the same.

I indeed downloaded the ISO twice from the official source, checked checksum just to double check.

Does the hardening script generate a log somewhere I can look at ? or else what I could do is re setup the VM, configure the auditd beforehand and then try executing the script for detailed logging on the actions the script performs

**Comment by konstruktoid** [comment]
There's no log created by default, but in `ubuntu.cfg` change `VERBOSE` to `VERBOSE='Y'` and run `sudo bash -x ubuntu.sh &>logfilename`

**Comment by w33ha-zxc** [comment]
Will try it out over the weekend and keep you posted.

**Comment by w33ha-zxc** [comment]
Closing this out, the issue was fixed by upgrading Hyper-V patches it seems.

Unable to reconstruct the issue. Will reopen if needed be.
