### ISSUE TITLE
[BUG] logrotate fails with `duplicate log entry for /var/log/{wtmp,btmp}` error

### ISSUE THREAD

**Issue by bob-rove** [konstruktoid/hardening#170]
**Describe the bug**

`/usr/sbin/logrotate /etc/logrotate.conf` exists with the following error:

```bash
error: /etc/logrotate.conf:30 duplicate log entry for /var/log/wtmp
error: /etc/logrotate.conf:37 duplicate log entry for /var/log/btmp
```

Worth noting that original issue seems to be coming from `logrotate` package: https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1915759
(TLDR: maintainers seem to come to conclusion to comment out `/var/log/[bw]tmp { ... }` blocks in `/etc/logrotate.conf` and rely on their equivalents in `/etc/logrotate.d/[bw]tmp`)

Although I'm not entirely sure if this constitutes for a bug, given that package-supplied `logrotate.conf` is being overwritten by the file from this repo, perhaps it's worth considering fixing it here now, while anticipating upcoming fix in `logrotate` package.

**To Reproduce**

Run `/usr/sbin/logrotate /etc/logrotate.conf` as called from `systemd` and `cron`.

**Expected behavior**

No errors and exit code `0`.

**System (lsb_release -a):**

```bash
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**

Same problem reported in `logrotate` package issue tracker: https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1915759

**Comment by konstruktoid** [comment]
Thanks again @bob-rove, will have a look at it as soon as possible.

**Comment by konstruktoid** [comment]
Updated the config file for logrotate @bob-rove to make it match upstream.

I believe https://bugs.launchpad.net/ubuntu/+source/logrotate/+bug/1915759 can be closed since an up-to-date Focal and Jammy don't include the duplicate code.

**Comment by bob-rove** [comment]
Cool stuff, thanks @konstruktoid ! 🙌
