### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kodiakz** [konstruktoid/hardening#196]
**Describe the bug**
Ubuntu 22.04 (Jammy) does not provide _aide.wrapper_ which is required by _config/aidecheck.service_

**To Reproduce**

- https://packages.ubuntu.com/jammy/all/aide-common/filelist
- https://packages.ubuntu.com/bionic/all/aide-common/filelist

**Expected behavior**
_aidecheck.service_ needs to be adjusted for Jammy

**System (lsb_release -a):**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by konstruktoid** [comment]
Thanks @kodiakz, I'll have a look

**Comment by konstruktoid** [comment]
Can you take a look at #197?

**Comment by kodiakz** [comment]
Looks good to me, thx!
