### ISSUE TITLE
Ubuntu 16.04 SSHD Config error

### ISSUE THREAD

**Issue by jasonmcintosh** [konstruktoid/hardening#22]
Line 22:

``` sed -i 's/.*Subsystem sftp.*/Subsystem sftp \/usr\/lib\/ssh\/sftp-server -f AUTHPRIV -l INFO/' "$SSHDFILE"```

On ubuntu 16.04 (not checked current) that should be openssh not ssh.
```  sed -i 's/.*Subsystem sftp.*/Subsystem sftp \/usr\/lib\/openssh\/sftp-server -f AUTHPRIV -l INFO/' "$SSHDFILE"```

**Comment by konstruktoid** [comment]
Thanks @jasonmcintosh, the path was incorrect for all versions.
Fixed in https://github.com/konstruktoid/hardening/commit/e2abd77af5f411f400a378a623c7dac2d0255b24
