### ISSUE TITLE
jenkins installation issue on linux ec2 

### ISSUE THREAD

**Issue by azharism** [konstruktoid/hardening#238]
Job for jenkins.service failed because the control process exited with error code. See "systemctl status jenkins.service" and "journalctl -xe" for details.

jenkins.service - Jenkins Continuous Integration Server
   Loaded: loaded (/usr/lib/systemd/system/jenkins.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sat 2023-02-11 20:34:49 UTC; 10s ago
  Process: 25165 ExecStart=/usr/bin/jenkins (code=exited, status=1/FAILURE)
 Main PID: 25165 (code=exited, status=1/FAILURE)

jenkins.service: main process exited, code=exited, status=1/FAILURE
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: Failed to start Jenkins Continuous Integration Server.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: Unit jenkins.service entered failed state.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: jenkins.service failed.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: jenkins.service holdoff time over, scheduling restart.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: Stopped Jenkins Continuous Integration Server.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: start request repeated too quickly for jenkins.service
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: Failed to start Jenkins Continuous Integration Server.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: Unit jenkins.service entered failed state.
Feb 11 20:34:49 ip-172-31-57-17.ec2.internal systemd[1]: jenkins.service failed.

please help sir to find the solution

**Comment by konstruktoid** [comment]
How is this issue related to this repository?

**Comment by azharism** [comment]
i am installing jenkinns on ec2 linux machine and facing this  isuue

**Comment by azharism** [comment]
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
amazon-linux-extras install epel 
amazon-linux-extras install java-openjdk11

using the above command facing issue kindly help to fix it

**Comment by konstruktoid** [comment]
Sorry, this hasn't got anything to do with this repository.
