### ISSUE TITLE
Question: su: Permision denied

### ISSUE THREAD

**Issue by esnavarro** [konstruktoid/hardening#241]
**Describe the bug**
**su: Permission denied**

**Expected behavior**
should be able to switch to another user account

**System (lsb_release -a):**
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

**Additional context**
I decided to perform the automated security hardening for my ubuntu 22.04 server, after I run the script (**ubuntu.sh**) I encountered an unexpected error.  When I tried to switch to another account using the "**su -l _username_**" command and input with the right password I received an error message  **su: Permission denied**

Is there a way to revert back to its normal state(remove the hardening) using the script? 

Thank you,

**Comment by konstruktoid** [comment]
Hi @esnavarro, the restriction is set by https://github.com/konstruktoid/hardening/blob/master/scripts/rootaccess#L30.
I recommend you to use `sudo -i -u username` instead since `su` has been superseded by sudo, which allows for better control regarding privileged access.
