### ISSUE TITLE
Documentation: functions in documentation does not reflect actual functions in the code 

### ISSUE THREAD

**Issue by egisan2019** [konstruktoid/hardening#243]
Some minor docs issues, which make harder to navigate the script, as function names differ:
function name disablemnt vs actual name f_disablefs
limits vs f_limitsconf
packages vs f_package_install
ctraltdel vs f_ctrlaltdel
compilers vs f_restrictcompilers
reboot vs f_checkreboot

Also missing some functions description in docs, which are implemented:
f_aptget_configure
f_sshconfig
f_package_remove
f_aa_enforce
f_aide_post
f_aide_timer
f_aptget_noexec
f_aptget_clean
maybe they are merged into other scripts?

Is it possible to identify implemented CIS controls?

**Comment by konstruktoid** [comment]
Thanks @egisan2019, and to be honest. This isn't minor.
Will start updating.

**Comment by konstruktoid** [comment]
Sorry for the delay @egisan2019, but the README has been rewritten.
Feel free to point out any mistakes.
