### ISSUE TITLE
[BUG] run the runTestHosts.sh fails with error

### ISSUE THREAD

**Issue by l3nnartt** [konstruktoid/hardening#246]
**Describe the bug**
if we start the runHostTests.sh we got an error:
`grep: ./*_*.bats: No such file or directory`

**To Reproduce**
sudo apt-get -y install bats
git clone https://github.com/konstruktoid/hardening.git
cd hardening/tests/
bash ./runHostTests.sh

**Expected behavior**
that the script runs correct(?)

**System (lsb_release -a):**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

**Additional context**
///

**Comment by konstruktoid** [comment]
Hi @l3nnartt and thanks for creating this issue. A fix is soon available.

**Comment by konstruktoid** [comment]
Should be fixed now.

**Comment by l3nnartt** [comment]
works, thanks for the quick reply!
