### ISSUE TITLE
Increase /var partitions

### ISSUE THREAD

**Issue by esnavarro** [konstruktoid/hardening#280]
Hi, 

Seeking your assistance on how to increase the partition for /var. I didn't expect this to happen. I've searched everywhere on the internet to get an idea and references. I tried to resolve it on my own but had no luck. For reference kindly see SC. Thanks

![image](https://github.com/konstruktoid/hardening/assets/124149393/ca729f71-48f1-4804-b4e1-5de8101fd703)

**Comment by konstruktoid** [comment]
Hi @esnavarro 

Is this in any way related to this repository?
