### ISSUE TITLE
[BUG] ping not available on minimized 22.04.2 installation.

### ISSUE THREAD

**Issue by funk-on-code** [konstruktoid/hardening#282]
**Describe the bug**
Selected Ubuntu Minimized from a fresh 22.04.2 ISO install, ping is not longer installed by default.

**To Reproduce**
Get to stage 13 from README, the following errors occur:
`
./scripts/timesyncd: line 1: dig: command not found
`
`
./scripts/timesyncd: line 36: ping: command not found
`

**Expected behavior**
Packages were found.

**System (lsb_release -a):**
Distributor ID: Ubuntu
Distribution: Ubuntu 22.04.2
Release: 22.04
Codename: jammy

**Additional context**
Installing **iputils-ping** fixes the problem, installing bind9-tools to get dig is a little heavy on the dependency side though.

**Comment by konstruktoid** [comment]
Hi @funk-on-code and thanks for reporting this.
I'll add `ping` and `dig` to https://github.com/konstruktoid/hardening/blob/master/ubuntu.sh#L22 in a couple of day. Unless you want to submit a PR?

**Comment by konstruktoid** [comment]
Sorry for the delay, I believe this is fixed now.
