### ISSUE TITLE
apt-get update

### ISSUE THREAD

**Issue by esnavarro** [konstruktoid/hardening#285]
Hi, 

After I performed and apply the hardening scripts on my machine, once I run the apt-get update I'm now getting this error.  Please see attached. Do you have any idea to resolve the issue I currently faced? Much appreciated your swift response. Thanks
![image](https://github.com/konstruktoid/hardening/assets/124149393/db95a9bb-8813-447a-a0ca-de38ecbeb6e0)

**Comment by konstruktoid** [comment]
Hi @esnavarro 
Can you `ping` or `dig`  any other sites? And please verify that the correct nameservers are set in `/etc/systemd/resolved.conf`.
