### ISSUE TITLE
Document Hardening Items

### ISSUE THREAD

**Issue by joelchen** [konstruktoid/hardening#3]
Would be good to have a list of items and descriptions for all hardening performed in the script documented in README or Wiki.

**Comment by konstruktoid** [comment]
Thanks for the comment @joelchen, I'll work on the documentation as soon as possible.

**Comment by konstruktoid** [comment]
Better late than never.
@joelchen, any improvements?

**Comment by joelchen** [comment]
@konstruktoid Yes, I see some improvements, thank you. Further improvements could be made for description or link to website of the softwares that are installed or removed, and because running this script caused my system in Docker to fail because of UFW and AppArmor, document additional steps to remedy this problem.

**Comment by konstruktoid** [comment]
@joelchen I'll add reference links.
But why would you run this in a Docker container?

**Comment by joelchen** [comment]
@konstruktoid I run this on Ubuntu servers, and Docker is installed on Ubuntu servers for running applications. There are problems with Docker containers when UFW and AppArmor are enabled.

**Comment by konstruktoid** [comment]
So do I @joelchen, and yes, there have been issues with Docker and UFW/AppArmor but UFW and AppArmor affects all system services and often requires modifications.

**Comment by pascalandy** [comment]
Same use case as @joelchen here.

**Comment by konstruktoid** [comment]
Thanks and again sorry for the late reply, vacation and such.
I understand this tries to assist in configuring `UFW` and `Docker` but opening all above ports is unnecessary and you'll need to configure an "Docker network" in additional to the present `FW_ADMIN` option.

**Comment by konstruktoid** [comment]
Closing, too many user specific variables.

**Comment by pascalandy** [comment]
That's why I propose a config about Docker installation y/n

But I absolutely understand that you don't want to manage this in this project. 

Cheers!
