### ISSUE TITLE
Bionic Beaver mount options change

### ISSUE THREAD

**Issue by rmharriman** [konstruktoid/hardening#32]
The server installer for Ubuntu 18.04 removed the ability to set partition mount options (rw, nousid, nodev, noexec). Is this something that can be handled in the hardening scripts? Probably in 08_fstab.

**Comment by konstruktoid** [comment]
Thanks @rmharriman, I'll look into it.

**Comment by konstruktoid** [comment]
Please test https://github.com/konstruktoid/hardening/pull/33 @rmharriman

**Comment by rmharriman** [comment]
Seems to be fixed. I verified using the test script before and after rebooting. /var/log/audit as a control failed the before and after, but /home and /var/log both passed after.

**Comment by konstruktoid** [comment]
Updated the branch with `/var/log/audit`
