### ISSUE TITLE
[BUG] Missing dot

### ISSUE THREAD

**Issue by Xavantex** [konstruktoid/hardening#323]
**Describe the bug**
Aptget scripts will not match.

**To Reproduce**
have Acquire::http::AllowRedirect option before running script, will not include the "false"/"true" in pattern.

**Expected behavior**
Full pattern supposed to match and be substituted.

**System (lsb_release -a):**

**Additional context**
Lazy ass bum CBA to change line 34 in aptget script from 's/.*Acquire::http::AllowRedirect*/......' to 's/.*Acquire::http::AllowRedirect.*/.....". Basically, there's a dot missing before the last asterisk.

**Comment by konstruktoid** [comment]
Thanks @Xavantex!
