### ISSUE TITLE
Nginx dont show web after hardening

### ISSUE THREAD

**Issue by zikkuratti** [konstruktoid/hardening#340]
After hardening my graylog nginx not available on ip got any advice how to bring it back?
netwstat -tulpn shows 80 443 listening but no access maybe you got idea which module can be troubled?

**Comment by konstruktoid** [comment]
Hi @zikkuratti, what does `ufw status verbose` say?

**Comment by konstruktoid** [comment]
And did it work?

**Comment by konstruktoid** [comment]
yeah, that's obviously broken. Did you follow https://github.com/konstruktoid/hardening?tab=readme-ov-file#howto?

**Comment by zikkuratti** [comment]
no you dont understand i clean them up and then i add only this my nginx brokeup

**Comment by konstruktoid** [comment]
Sorry, I'm not following. 
What steps did you take? 
Do you have any logs related to nginx stop working?
What are the actual error messages?
