### ISSUE TITLE
Configure TimeZone

### ISSUE THREAD

**Issue by pascalandy** [konstruktoid/hardening#4]
Hi,
I think it would make sense to add a TIME_DATE flag in ubuntu.cfg 

In my specific case it would be:

```
TIMEDATECTL='America/New_York'
```

### In my setup I use this:
```
sudo apt-get -qqy install ntp ntpdate --no-install-recommends
sudo timedatectl set-timezone America/New_York
sudo timedatectl set-ntp yes
echo && echo -e "Verify that the timezone has been set properly"
timedatectl
```

**Comment by konstruktoid** [comment]
Thanks again @pascalandy, I'll add `TIMEDATECTL` later on, but I'm not sure installing `ntp` is necessary since I'll focusing on using `systemd` functions as often as possible.

**Comment by konstruktoid** [comment]
Present in the development branch.

**Comment by pascalandy** [comment]
Great, I was about to deploy few machines today

**Comment by konstruktoid** [comment]
Closes with https://github.com/konstruktoid/hardening/commit/a80c348af2da225a5bf63409884efb2e1323a168
