### ISSUE TITLE
disconnected during upgrade packages

### ISSUE THREAD

**Issue by frederikbosch** [konstruktoid/hardening#40]
I am wondering how I can prevent that I get disconnect from `ssh` when upgrading packages through `apt upgrade`. This happens when packages have not been updated for a while. Security updates are activated through this installation library, but feature/bug updates will have to be installed manually. And during this process I am disconnected before the installation was finished.

**Comment by konstruktoid** [comment]
If the update takes more than 5 minutes, and gets you disconnected, I suggest you should try running the update using `screen` or `tmux`.

**Comment by frederikbosch** [comment]
Thanks, I believe I had problems with that before due to systemctl setting that closed the user session, even when I started tmux/screen. I cannot recall any more. Therefore I close it for now.
