### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [konstruktoid/hardening#41]
Hi, @konstruktoid 

I noticed that this project has no logo. bir logo tasarladım. I can share it with you if you want. What do you say? I'll wait for feedback. 
Best regards.

**Comment by konstruktoid** [comment]
Hi @reallinfo, and so sorry for the long delay.
Sounds like a fun idea, feel free to submit a proposal.

**Comment by reallinfo** [comment]
I have designed a logo that represents the function of the project in a good way. What do you think?

![hardening](https://user-images.githubusercontent.com/36298335/58286933-80cec600-7db8-11e9-9d97-0b6db9931338.jpg)

**Comment by konstruktoid** [comment]
Cool! I really like the top one.

**Comment by reallinfo** [comment]
Thanks, i sent a pr for all variations. But i can't update the readme file.  If you want it, you can update. if you need a logo for other project, freel free to say me. Have a nice day!

**Comment by konstruktoid** [comment]
Thank you @reallinfo!

**Comment by konstruktoid** [comment]
Closing issue, thanks @reallinfo!
