### ISSUE TITLE
Not able to run the hardening script, throws Please read the code. Exiting.

### ISSUE THREAD

**Issue by taragurung** [konstruktoid/hardening#448]
**Describe the bug**
When i run the sudo bash ubuntu.sh i get the error message 
"`Please read the code. Exiting`." 
not clear what the exact problem is

**To Reproduce**

- create a EC2 machine with ubuntu 22.04
- Follow the instruction as stated in the documentations 
- make some changes in config, just another another IP address in the ubuntu.cfg with space separator
- run the script `sudo bash ubuntu.sh`

**Expected behavior**
- script running successfully and hardening the VM

**Additional context**
**Systen details:** Ubuntu 22.04.4 LTS

**Comment by konstruktoid** [comment]
Hi @taragurung 

The README says that you need to change the configuration options in the `ubuntu.cfg` file.

https://github.com/konstruktoid/hardening/blob/master/README.adoc#L50

And on https://github.com/konstruktoid/hardening/blob/master/ubuntu.cfg#L14: "Add something just to verify that you actually glanced the code"

**Comment by taragurung** [comment]
The docs says "Change the configuration options in the ubuntu.cfg file" So i made change in first line in the config. 
**May be the line is confusing.** 

Thanks for the reply, that helped!  @konstruktoid
