### ISSUE TITLE
Can't exec within /tmp while running script

### ISSUE THREAD

**Issue by onsetsoftware** [konstruktoid/hardening#52]
Periodically within the script I get:
```
Preconfiguring packages ...
Can't exec "/tmp/<SOME-FILENAMEHERE>": Permission denied at /usr/share/perl/5.26/IPC/Open3.pm line 178.
open2: exec of /tmp/<SOME-FILENAMEHERE> configure  failed: Permission denied at /usr/share/perl5/Debconf/ConfModule.pm line 59.
```
It is not always the same file within the `tmp` directory, but it is always the same 2 perl scripts. Presumably this is because the `noexec` flag is set on the `tmp` partition. Is this correct?

**Comment by konstruktoid** [comment]
Hi @onsetsoftware, that's correct. Afaik, this hasn't really affected things and after apt has been setup `/tmp` should remount properly.

**Comment by onsetsoftware** [comment]
Hi @konstruktoid, thanks for your reply. So should I assume this is actually not an issue at all? It appears that perhaps packages are not being installed properly?

**Comment by onsetsoftware** [comment]
Wonderful. Thanks very much indeed.
