### ISSUE TITLE
[BUG] Can't use Google-Chrome anymore after the hardening was done 

### ISSUE THREAD

**Issue by madiba237** [konstruktoid/hardening#523]
**Describe the bug**
Google chrome worked just fine before the hardening, after it impossible to launch it no matter the user (root...)

**To Reproduce**
launching google-chrome from the terminal  result to this message showing up 👍
 /usr/bin/google-chrome: error while loading shared libraries: libdl.so.2: cannot open shared object file:  Permission denied
 
**Expected behavior**

google-chrome browser should be launched .

**System (lsb_release -a):**

Distributor ID: Ubuntu
Description: Ubuntu 24.04.1 LTS
Release:       24.04
Codename:  noble

**Additional context**

After stoping and disabeling apparmor.service it still doesn't work

**Comment by konstruktoid** [comment]
Hi @madiba237 , I have not in any way tested the script on a client running graphical applications.

Can you attach some relevant journal logs as well?

**Comment by madiba237** [comment]
sorry for the late reply i was overwhelmed by other projects here are lines in my logs that concern google chrome 


2024-11-26T15:21:55.301915+01:00 PA-UBUNTU gnome-shell[20638]: Error fetching user unit for own pid: 3
2024-11-26T15:21:55.357382+01:00 PA-UBUNTU google-chrome.desktop[22394]: /usr/bin/google-chrome-stable: error while loading shared libraries: libdl.so.2: cannot open shared object file: Permission denied


Great thanks for the endeavors

**Comment by konstruktoid** [comment]
no worries, but those log messages was included in you issue as well. 
does any logs indicate it's an `apparmor` issue`? what other relevant logs are there?

what does `ls -l /usr/lib/x86_64-linux-gnu/libdl.so.2` return?

since the script is one-shot, have you tried re-installing Chrome?

**Comment by madiba237** [comment]
Greeting , 
sadly i do not have the VM no more so i won't provide those logs , but i can assure you the issue comes from app armor

**Comment by konstruktoid** [comment]
> After stoping and disabeling apparmor.service it still doesn't work

> i can assure you the issue comes from app armor

Could you then list the AppArmor profiles in use?

**Comment by konstruktoid** [comment]
Try running `sudo aa-complain chrome`.
To update the profile afterwards, run `aa-logprof` and then enforce the profile again.

**Comment by madiba237** [comment]
Hi @konstruktoid  i was able to launch chrome , after running the commands you suggested , i am going for further investigations 
i need to allow  regular users to launch chrome too
Thx
