### ISSUE TITLE
[BUG] Cant connect to  Forticlient no more (OpenVpn)

### ISSUE THREAD

**Issue by madiba237** [konstruktoid/hardening#535]
I can't connect to th e Forticlient VPN , i do not know exactly if is due to apparmor or something else in the hardening

**Comment by konstruktoid** [comment]
and you have tried https://github.com/konstruktoid/hardening/issues/523#issuecomment-2505677042 as the last time?

**Comment by madiba237** [comment]
Hi
 i had the wrong config on my vpn , neither apparmor nor anything else was blocking me 
Thankq you very much
