### ISSUE TITLE
[BUG] sudo can't be used after hardening the machine

### ISSUE THREAD

**Issue by GauthierPLM** [konstruktoid/hardening#544]
**Describe the bug**
I receive the following error after running the hardening script on Ubuntu 24.04:

```sh
$ sudo reboot
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

**To Reproduce**

1. Setup a fresh ubuntu 24.04 machine.
2. Change SSH port to 12322 (or any other port)
3. use any as FW_ADMIN value.
4. run `sudo bash ubuntu.sh`
5. once completed, try to run a command using sudo (ex: `sudo reboot`). The command will be rejected with the error above

**Expected behavior**

The `sudo` command should work as expected.

**System (lsb_release -a):**

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

**Additional context**

```sh
/usr/bin$ ls -ln sudo
-rwxr-xr-x 1 0 0 335120 Apr  8  2024 sudo
```

**Comment by GauthierPLM** [comment]
Temporary solution:
- run the hardening as root and run `chmod 4755 /usr/bin/sudo`
- use a rescue mode to access the system and run the above command.

**Comment by konstruktoid** [comment]
Thank you  @GauthierPLM  for reporting this.
`sudo` was added by mistake in https://github.com/konstruktoid/hardening/pull/540/commits/70d66b238c14fe3648eb9534fc5d2b2dde9331ae
