### ISSUE TITLE
Aide Service duplication

### ISSUE THREAD

**Issue by acurrieclark** [konstruktoid/hardening#55]
I was inspecting the aide logs for my server today and realised that AIDE currently runs twice a day. At midnight, and then again at 6:30am.

It seems to me that the hardening script install a service to be run at midnight, while the standard AIDE configuration adds a daily cron job

My question is, are these serving different purposes, or is one of them redundant?

**Comment by konstruktoid** [comment]
Hi @acurrieclark, and nice catch.
This should be fixed very shortly.

**Comment by acurrieclark** [comment]
Well, that was impressive! Thanks for the swift response
