### ISSUE TITLE
PSAD? Firewall AntiDDOS Atack?

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#67]
Hi

Will be add PSAD and firewall AntiDDOS Atack rules ?

Best Regards

**Comment by konstruktoid** [comment]
I'm so so sorry for the late reply @hellresistor, I've completely missed this issue.

I'm not currently planning to add `psad` due to the configuration complexity, but adding some basic anti-DDOS `ufw` rules (in addition to the current `sysctl` rules) might be added in the future.

**Comment by hellresistor** [comment]
Hi @konstruktoid , No problem sometimes I can came here!

Well Can I help with something with PSAD.
To a Anti DDOS Attack I have read this 2 times and seems very very strong (if not missing me nothing)! (https://github.com/anti-ddos/Anti-DDOS)

keep in touch

**Comment by hellresistor** [comment]
Well. 
Na mesma, adicionei suporte PSAD. Corrige-me se está tudo no sitio ;)
