### ISSUE TITLE
[Enchantment] iptables and anti-ddos attack?

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#72]
Have checked this two times.

Maybe a good iptables config

https://github.com/anti-ddos/Anti-DDOS/blob/master/anti-ddos.sh

**Comment by konstruktoid** [comment]
It will require a lot of configuration, e.g https://github.com/anti-ddos/Anti-DDOS/blob/master/anti-ddos.sh#L308-L331 might not be necessary, but the general idea is good.

**Comment by konstruktoid** [comment]
https://github.com/anti-ddos/Anti-DDOS/blob/master/anti-ddos.sh#L347-L350 isn't really a good selling point, and https://github.com/anti-ddos/Anti-DDOS/blob/master/anti-ddos.sh#L384-L428 is even more open ports.

**Comment by hellresistor** [comment]
yes i saw it! But just some adjustments and take the idea/orientation.
