### ISSUE TITLE
13 Configure APT

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#74]
On same last .log

[13] Configure APT
/etc/apt/apt.conf.d/10periodic:APT::Periodic::AutocleanInterval "0";

Should not be show.

**Comment by konstruktoid** [comment]
That's expected, https://github.com/konstruktoid/hardening/blob/master/scripts/10_aptget#L43-L47, since I don't silence the `grep` output.
It should result in `APT::Periodic::AutocleanInterval "7";` present in the same file.
