### ISSUE TITLE
[Question] Postfix

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#76]
Hi friend.

What is the goal of using postfix? 
Just to send notifications emails? or will run a mail server?

**Comment by konstruktoid** [comment]
Hi there!
it's just there to handle the internal mails. It will run a mail server (postfix) but only listening on the loopback interface

**Comment by hellresistor** [comment]
Ok I thought was to send only admin notifications.
Have a way to send mail only method with 'msmtp' and TLS authentication. (Using gmail example)

**Comment by konstruktoid** [comment]
Sorry, I don't understand what the issue is.

**Comment by hellresistor** [comment]
accidently reopened .
