### ISSUE TITLE
Possible mistake with 'w' command getting IP

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#78]
Well.. I have installed "physically" on vm machine with `AUTOFIL=Y`
![noW](https://user-images.githubusercontent.com/50468493/85329221-00522b80-b4ca-11ea-826f-7eed5b5f8de7.png)

Detected 'w' command will not get the IP, because exist no connections/sessions active.

maybe should change this line: `USERIP="$($WBIN -ih | awk '{print $3}' | head -n1)"`

**Comment by konstruktoid** [comment]
Thanks for catching this, I believe it's fixed with https://github.com/konstruktoid/hardening/commit/f4a9c30126d925840109e73756f2d2f4fb383488

**Comment by hellresistor** [comment]
nop. Getting the Gateway IP ;)
machine IP: 192.168.52.128
getting ip: 192.168.52.1

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/hardening/blob/master/ubuntu.sh#L50 is the correctly updated version.

can you run `hostname -I | sed -E 's/\.[0-9]+ /.0\/24 /g'`?
it's overkill, but it's a crude way to catch all local networks if `w` doesn't get anything useful

```
~$ hostname -I
10.0.2.15 
~$ hostname -I | sed -E 's/\.[0-9]+ /.0\/24 /g'
10.0.2.0/24 
```

**Comment by hellresistor** [comment]
After installation.. YES. you get right IP during installation. Getting 192.168.52.1
![wronip](https://user-images.githubusercontent.com/50468493/85885784-d1df9380-b7dc-11ea-837a-d71c52d47a5f.png)
![wronip2](https://user-images.githubusercontent.com/50468493/85885787-d2782a00-b7dc-11ea-89f7-06ea344ae62b.png)

**Comment by hellresistor** [comment]
why have discuss this before ( what was i remmebered)

this method work like a charm because will search for device IP 
`USERIP="$($WBIN -ih | awk '{print $3}' | head -n1)"`

**Comment by hellresistor** [comment]
works with this line (I think we have this discussion before ?! no? )

`USERIP="$(ip route get 8.8.8.8 | awk -F"src " 'NR==1{split($2,a," ");print a[1]}')"`

**Comment by konstruktoid** [comment]
yeah, and that requires access to an external resource which I'm trying to avoid.

**Comment by hellresistor** [comment]
Try this!
`USERIP="$(hostname --all-ip-addresses)`

**Comment by konstruktoid** [comment]
https://manpages.ubuntu.com/manpages/focal/en/man1/hostname.1.html
`-I, --all-ip-addresses`

**Comment by hellresistor** [comment]
and about 2nd line?

**Comment by konstruktoid** [comment]
`USERIP="$(ip -o addr show up primary scope global | while read -r num dev fam addr rest; do echo ${addr%/*}; done)"`?
Overly complicated.

**Comment by hellresistor** [comment]
> `USERIP="$(ip -o addr show up primary scope global | while read -r num dev fam addr rest; do echo ${addr%/*}; done)"`?
> Overly complicated.

well. but does what is needed :octocat:

**Comment by konstruktoid** [comment]
`hostname -I | sed -E 's/\.[0-9]+ /.0\/24 /g'` doesn't work?

**Comment by hellresistor** [comment]
like command "says"
will replace the ip to a subnet ip` 192.168.1.0/24`

**Comment by konstruktoid** [comment]
Yes, and that's the point, if we don't get a valid address from the `w` command, e.g. when installing locally, we'll allow the `/24` subnet so we can administer the machine afterwards of ssh. 

https://github.com/konstruktoid/hardening/blob/master/ubuntu.sh#L47-L51

```
    USERIP="$($WBIN -ih | awk '{print $3}' | head -n1)"

    if [[ "$USERIP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      ADMINIP="$USERIP"
    else
      ADMINIP="$(hostname -I | sed -E 's/\.[0-9]+ /.0\/24 /g')"
    fi
```
