### ISSUE TITLE
ufw ssh rule issue ?

### ISSUE THREAD

**Issue by hellresistor** [konstruktoid/hardening#79]
detected this issue.

```
@testubuntu20:~$ sudo ufw status numbered
Status: active

     To                         Action      From
     --                         ------      ----
[ 1] 22/tcp                     ALLOW IN    127.0.0.1                  (log)

```

should be anywhere instead 127.0.0.1 ?

**Comment by konstruktoid** [comment]
@hellresistor, I can't really help without information. How did you use the script? Was does a log say? Are you using the script locally?

**Comment by hellresistor** [comment]
I will try next time Give all info.

This issue i have been detected executing script localy/physic with Autofil="Y"

well.. the alzheimer is attacking me now.. i can remember what i have done..

I will try reproduce this again (not today...) and if confirms then I will enable this thread.
