### ISSUE TITLE
Support for EC2?

### ISSUE THREAD

**Issue by rmurillo21** [konstruktoid/hardening#8]
Looks great.  Any reason this would not work on an AWS EC2 instance? I noticed Grub/bootloading not sure how that would work on a virtual server. Thanks

**Comment by konstruktoid** [comment]
Hi @rmurillo21, I don't have an EC2 to test it on for the moment, but the only changes that are made relating to GRUB is https://github.com/konstruktoid/hardening/blob/master/scripts/22_auditd#L8 and that shouldn't break anything.

**Comment by rmurillo21** [comment]
Thanks.   I will try it on an EC2 instance on Ubuntu and report back.

**Comment by rmurillo21** [comment]
Working great on EC2 Ubuntu 16.06! I had to tweak the KexAlgorithms list to support my local putty but that was about it. I has used commas as a delim on FW_ADMIN, which was not correct - it wants spaces. 
Thanks

**Comment by konstruktoid** [comment]
Thanks for testing this @rmurillo21, updated the README regarding the spaces.

**Comment by sentient** [comment]
@rmurillo21 thanks for confirming it worked on EC2. I have one question how do you actually got this started on an EC2 instance. It is just the first step how do you install the ubuntu installation software on an EC2 image. Are not all AMI images already pre-configured with an OS?  

Just wondering what steps you took

Thanks


> Working great on EC2 Ubuntu 16.06! I had to tweak the KexAlgorithms list to support my local putty but that was about it. I has used commas as a delim on FW_ADMIN, which was not correct - it wants spaces.
> Thanks

**Comment by rmurillo21** [comment]
I just download the package at startup, via a userdata script. Works great.
