### ISSUE TITLE
Kernel Updates

### ISSUE THREAD

**Issue by wyattconsulting** [konstruktoid/hardening#87]
What do I have to do to get a newly installed kernel to boot? I have run update-grub and it sees that new kernel, but doesn't show up on the list on boot. 

Thank you!

**Comment by konstruktoid** [comment]
Hi @wyattconsulting, it doesn't show up on the list as in the boot menu or you aren't able to the new kernel?

**Comment by wyattconsulting** [comment]
Thanks for getting back to me so quickly. Yes, it doesn't show up on the boot menu despite everything else about updating appearing to work just fine. When I run update-grub it even shows it is recognizing the new kernel, but still new boot menu entry.

**Comment by konstruktoid** [comment]
Sorry for the delay, but I can't verify this.
Installed a Ubuntu 20.04 server from ISO, ran the script, added another kernel, `update-grub`, reboot.


![ubuntu2004-vanilla](https://user-images.githubusercontent.com/7956715/96190376-ade1c280-0f31-11eb-9c7a-85224d3558ce.png)
![ubuntu2004-update-grub](https://user-images.githubusercontent.com/7956715/96190386-b20de000-0f31-11eb-98ee-bdb458136489.png)
![ubuntu2004-post](https://user-images.githubusercontent.com/7956715/96190396-b6d29400-0f31-11eb-96c5-94dcb58d8021.png)

**Comment by wyattconsulting** [comment]
I am super impressed with this effort man! Thank you so much. Let me fool around with my build and see if I can get it to work, otherwise I'll wipe and start fresh and see if I can reproduce. This is just my side project getting a little deeper into hardening Linux, but I really appreciate the help and support. I will be following and hopefully contributing to the project at some point. Take care!
