### ISSUE TITLE
08_fstab line 13 quick fix

### ISSUE THREAD

**Issue by JtheDBA** [konstruktoid/hardening#89]
Probably doesn't need a pull request, but /var/tmp expression needed added to line 13.

If /var/tmp is in fstab it need to be removed on line 13 else when the check and adds on lines 31-33 will result in two /var/tmp mounts in /etc/fstab

grep -v -E '[[:space:]]/boot[[:space:]]|[[:space:]]/home[[:space:]]|[[:space:]]/var/log[[:space:]]|[[:space:]]/var/log/audit[[:space:]]|[[:space:]]/var/tmp[[:space:]]' /etc/fstab > "$TMPFSTAB"

Cheers. Stay safe.
J the DBA

**Comment by konstruktoid** [comment]
Thanks @JtheDBA, commited in https://github.com/konstruktoid/hardening/commit/8a0e34c4bba6d6dd02a9a5b2caa67a9bb59111e8

**Comment by JtheDBA** [comment]
Verified commit 8a0e34c. Issue resolved.
