### ISSUE TITLE
net-tools package has to be installed

### ISSUE THREAD

**Issue by JtheDBA** [konstruktoid/hardening#90]
This, again, likely does not need a pull request.

The default installation of Ubuntu server does not include the package `net-tools` so the hardening/ubuntu.sh script fails immediately. A simple `apt install -y net-tools`  is all that is needed.

I am using a VirtualBox VM and installing from the `ubuntu-20.04.1-live-server-amd64.iso` disc using all defaults except for the partitioning where I use a LVM physical volume on a single disk and create logical volumes for all mounts in the readme.md ...

This can probably be added in one of the early scripts that define the functions or the main installation script.

Thanks and stay safe.

**Comment by konstruktoid** [comment]
Hi again,
This should be catched by https://github.com/konstruktoid/hardening/blob/master/ubuntu.sh#L22-L34.
