### ISSUE TITLE
[QUESTION] VM rebooted during apt update

### ISSUE THREAD

**Issue by frederikbosch** [konstruktoid/hardening#95]
I have a hardened 18.04 machine, made more than a year ago @ commit bd559d812c51514023b1f36f400140d2c301e36e. Last week there were [two security updates for systemd](http://changelogs.ubuntu.com/changelogs/pool/main/s/systemd/systemd_237-3ubuntu10.50/changelog), and this caused my VMs to be rebooted. I believe it was the udev/libudev update that caused the reboot. But by what setting is getting triggered? My guess would be that is a auditd setting. Do you have any idea?

**Comment by konstruktoid** [comment]
Hi @frederikbosch 
Did the host reboot or halt? It could be the audit configuration that triggers a halt when then disk gets full.

**Comment by frederikbosch** [comment]
Hi @konstruktoid. Nope, it was the update of either udev or libudev that triggered the reboot. So I found out that udev is the device manager for the Linux kernel. Maybe updating the package causes the devices to be reloaded which is not allowed by the audit configuration?

**Comment by konstruktoid** [comment]
The audit system could cause a halt if the log partition gets full. 
Otherwise I would check the `needrestart` configuration, but that shouldn't cause a reboot.

Any pre-reboot logs or dmesg messages?
