### ISSUE TITLE
rsyslog : imudp: Could not create udp listener

### ISSUE THREAD

**Issue by GordonSasha** [konstruktoid/hardening#97]
Hi Thomas, 
you are making a great job - thank you very much. 
I have installed the version v1.0.0 on our device and now testing the
functionality of all the features under hardening. I am currently 
investigating the syslog problem and cannot figure out
what is happening. I would be very grateful if you can help me with this.

Problem:
=======
rsyslog imudp plugin can't create udp listener
/*-----------------------------------------------------------------*/
$ sudo systemctl status rsyslog.service
● rsyslog.service - System Logging Service
     Loaded: loaded (/lib/systemd/system/rsyslog.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-08-26 08:06:26 UTC; 8s ago
TriggeredBy: ● syslog.socket
       Docs: man:rsyslogd(8)
             https://www.rsyslog.com/doc/
   Main PID: 3980 (rsyslogd)
      Tasks: 4 (limit: 9281)
     Memory: 1.0M
     CGroup: /system.slice/rsyslog.service
             └─3980 /usr/sbin/rsyslogd -n -iNONE

Aug 26 08:06:26 tfence-sideB systemd[1]: Started System Logging Service.
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: create UDP socket bound to device failed: Operation not permitted [v8.2001.0]
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: create UDP socket bound to device failed: Operation not permitted [v8.2001.0]
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: No UDP socket could successfully be initialized, some functionality may be disabled.  [v8.2001>
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: imudp: Could not create udp listener, ignoring port 514 bind-address (null). [v8.2001.0]
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: imudp: no listeners could be started, input not activated.  [v8.2001.0]
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: activation of module imudp failed [v8.2001.0 try https://www.rsyslog.com/e/-3 ]
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: rsyslogd's groupid changed to 110
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: rsyslogd's userid changed to 104
Aug 26 08:06:26 tfence-sideB rsyslogd[3980]: [origin software="rsyslogd" swVersion="8.2001.0" x-pid="3980" x-info="https://www.rsyslog.com">
/*-----------------------------------------------------------------*/

Testing configuration:
======================

      Client1       |<========== Tested Device (tgate) ========>|            SRV
  syslog message -->|--> eth0  -----> use imudp  ---> eth1  ----|--> syslogserver
                    |  10.0.0.2                     172.16.1.2  |    172.16.1.50  
                    |-------------------------------------------|
                    
  Client1 $ logger --server 10.0.0.2 --udp --port 514 "$i) udp message from Client1";
  
  Tested Device (tgate) config:
	/etc/rsyslog.d/10-relay.conf :
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/	
$template msg_format, "%rawmsg%\n"
module(load="builtin:omfwd" Template="msg_format")
module(load="imudp")
input(type="imudp" port="514" device="eth0" ruleset="rs1")
Ruleset(name="rs1") {
action(type="omfwd" target="172.16.1.50" port="514" protocol="udp")
& stop
}
/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
with tcpdump I see the packages are arriving to the "eht0":
$ sudo tcpdump -i eth0 -nn -v udp and port 514
but "eth1" does not received them:
$ sudo tcpdump -i eth1 -nn -v udp and port 514 

Versions:
hardening:  v1.0.0 downloaded 14 apr 2021 
Tested Device (tgate) OS:
tgate :$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

rsyslog verion: 
rsyslogd: version 8.2001.0

If you have any ideas, suggestions, or you know another way to solve the problem, I would love to hear them. 
Thank you in advance

**Comment by GordonSasha** [comment]
Sorry for the delay and silence. I was ill. 
At your request,
[rsyslog_config.zip](https://github.com/konstruktoid/hardening/files/7111093/rsyslog_config.zip)
 sending you syslog configuration files
Sorry again and thanks in advance

**Comment by konstruktoid** [comment]
No need to apologise, glad you've gotten better.

I'll have a look at the config as soon as possible.

**Comment by GordonSasha** [comment]
Thanks a lot for your help. I opened additional bug about apt error. But
look like I know what's a problem. I can check it only at the Thursday. We
on holiday s vacation
Thanks

**Comment by konstruktoid** [comment]
Check the `device` setting on ther servers. That one of the reason that error occured.

I also tested and got it working with a rewritten config file.

![image](https://user-images.githubusercontent.com/7956715/132345628-5a3187c7-0f61-49df-a1e7-bc307af2ae61.png)

**Comment by GordonSasha** [comment]
Sorry for the delay and silence. I was ill. 
At your request,
[rsyslog_config.zip](https://github.com/konstruktoid/hardening/files/7111093/rsyslog_config.zip)
 sending you syslog configuration files
Sorry again and thanks in advance

**Comment by GordonSasha** [comment]
Hi, I found when problem is appearing. One of the apparmor profiles prevent to create UDP socket of the rsyslog. It happend in f_aa_enforce() function.

**Comment by GordonSasha** [comment]
the solution is : 
echo "capability net_raw," > /etc/apparmor.d/local/usr.sbin.rsyslogd

**Comment by konstruktoid** [comment]
> the solution is :
> echo "capability net_raw," > /etc/apparmor.d/local/usr.sbin.rsyslogd

great catch, i can add that check if you don't want to submit a PR.
pushing upstream?

**Comment by GordonSasha** [comment]
I think you can add it better than me.
