### ISSUE TITLE
Script 17_Packages: if the VM is a VirtualBox one, it installs the guest-utils 6.1.22, but we are already at 6.1.26

### ISSUE THREAD

**Issue by Thumpermat** [konstruktoid/hardening#99]
Not sure if you can do anything about this as it is probably the package manager not having the latest version.

**Comment by konstruktoid** [comment]
Yeah, not sure what I can do about that.
It's a bit odd though since https://github.com/konstruktoid/hardening/blob/master/scripts/10_aptget#L1-L13 updates the `apt` cache and 6.1.26 shouldn't be overwritten by a lower version.
